### ISSUE TITLE
Watch App download without having Pebble/Rebble installed

### ISSUE THREAD

**Issue by IzzySoft** [C-D-Lewis/dashboard#10]
On its main page, *Dashboard* offers a button labeled "INSTALL/UPDATE WATCHAPP" to install its Pebble counter-part on the watch. I assume that, with the Pebble/Rebble app installed on the device, Pebble/Rebble "catches" that link and redirects it to its corresponding view, offering the user to install the watchapp.

Now, some Pebble users (like me) do not have that Pebble/Rebble app installed on their devices, but instead use e.g. [Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge). All we see when tapping that button is a web browser – which curently does not offer to download/install the PBW:

[<img src="https://user-images.githubusercontent.com/6781438/74111367-88c3d580-4b94-11ea-9ecb-72eaf76b520f.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111367-88c3d580-4b94-11ea-9ecb-72eaf76b520f.jpg)

Could you please include the URL parameter `dev_settings=true` with that link? That causes an additional section being included with the web page, enabling us to download the PBW and then install it e.g. using Gadgetbridge's installer:

[<img src="https://user-images.githubusercontent.com/6781438/74111571-e7d61a00-4b95-11ea-83eb-4411e5bfe486.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111571-e7d61a00-4b95-11ea-83eb-4411e5bfe486.jpg) [<img src="https://user-images.githubusercontent.com/6781438/74111675-c45f9f00-4b96-11ea-992e-72c986d6f931.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111675-c45f9f00-4b96-11ea-992e-72c986d6f931.jpg)

Thanks in advance!

**Comment by C-D-Lewis** [comment]
I can do this! I will also try and restore the old sideload method using the `pebble://` device protocol, but no promises. The PBW can be found in this repo however in `assets/releases`.

**Comment by IzzySoft** [comment]
Whichever you prefer, as long as one can install the latest PBW :smile:

**Comment by C-D-Lewis** [comment]
Implemented, will be in next release. Also added a GitHub button...

**Comment by IzzySoft** [comment]
Cool! Looking forward to that next release then :smiley:

**Comment by C-D-Lewis** [comment]
Sorry for the delay, going to release this today.
