### ISSUE TITLE
Ringer Request not working

### ISSUE THREAD

**Issue by milan0-nbg** [C-D-Lewis/dashboard#12]
the ringer request does not change the state on the phone.

Phone: Huawei P10, Android 9.0, Emui Version 9.1
Pebble: Time Steel, FW4.4

Dashboard 4.12 still working fine

**Comment by C-D-Lewis** [comment]
Is this an issue with Dashboard v4.15 (most recent)?

**Comment by C-D-Lewis** [comment]
I found that is wasn't possible to set to Silent unless the app has permission for modifying Do Not Disturb settings. I added this a test build - please try it!

**Comment by milan0-nbg** [comment]
Yes. With 4.15 ist was possible to switch between loud and vibration. Only "set to silent" was not possible.
With the permission everything works fine. Thx for your work!

**Comment by C-D-Lewis** [comment]
Will release fix for this permission today
