### ISSUE TITLE
watchapp frozen on loading via gadgetbridge

### ISSUE THREAD

**Issue by p4t44** [C-D-Lewis/dashboard#13]
I use my Pebble with Gadgetbridge on Android and used to use Dashboard fine. Sometime ago (around the time I updated to Android 10, this may or may not be the cause) it stopped working. Upon launching the watchapp it now just hangs on the white logo with black background loading screen. I have tried reinstalling both apps numerous times including on the latest versions and it hasn't worked.

Today I tried of with the Pebble app (with Rebble) and it did work however as soon as I switched back to GadgetBridge it stopped working again.

Any help would be appreciated, I really like the dashboard app (the find phone function has saved my phone a couple of time) and would love to get it working again. 

Thank you

**Comment by C-D-Lewis** [comment]
I have not changed at all how the app interacts with system broadcasts (how it has always hooked into the Pebble app via pebblekit-android Intents), so perhaps related to changes in the SDK. Not sure where to start. Does it work with an older version (found in `assets/releases`)?

**Comment by p4t44** [comment]
I tried some older versions and none work. I think this issue seems to occur with any version of Dashboard through Gadgetbridge on Android 10 / Q. Is there any way I can collect logs to try and debug the issue?

Thank you

**Comment by p4t44** [comment]
So I had another look into this and it turns out I forgot to turn on PebbleKit integration in GadgetBridge settings. Sorry for the issue, I should have been more thorough in checking before posting here.

Thank you for making such a great app!

**Comment by C-D-Lewis** [comment]
I love a happy ending!
