### ISSUE TITLE
Data toggle is not working

### ISSUE THREAD

**Issue by baranyaib90** [C-D-Lewis/dashboard#3]
Hi,
First of all: thank you, for this amazing app, very good job!
Sadly, the Data toggle option is not working for me :(
I have Dashboard v4.9, I guess it's the latest.
I also have SuperSU and enabled the Data toggle in the "About menu" and also "Test Root Access" worked: "Root access test succeeded!".
But sadly, when I click on the Data tile in the pebble app, the transaction times out and nothing changes. It can not toggle the mobile net.
If I retry, than I get "Data request already in progress."
My phone's is a Lenovo P70 with Android 6.0.1, CyanogenMod 13.0.
Could you please fix it somehow?
Thank you in advance!
(Other data enablers are working with root rights, like PowerToggles.)
Br, Balazs

**Comment by C-D-Lewis** [comment]
Hi @baranyaib90, thanks for the report. You can see in [this line](https://github.com/C-D-Lewis/dashboard/blob/925f8e1f56279cb57600d6d23065b1480ee67bad/android/DashboardRedux/src/main/java/fragment/About.java#L103) that the 'Root access test succeeded!' message appears when the root library I'm using (Root Tools) tells me that root access is available. 

In [this file](https://github.com/C-D-Lewis/dashboard/blob/master/android/DashboardRedux/src/main/java/cl_toolkit/Root.java#L46) you can see the method used to switch the Data toggle. If you can connect a logcat (through the Android SDK tools, or Android Studio) and find an instance of the linked line's log output, we can begin to see if it worked or not. 

If not, I can possibly try and instrument this part of the app a bit more, and give you a version to test. But no guarantees, I'm afraid - it's a hack!

**Comment by baranyaib90** [comment]
Hi,
I have logs: [log.txt](https://github.com/C-D-Lewis/dashboard/files/1083246/log.txt)
Exit code is zero: "cl_toolkit.Root: Root mobileDataEnabled exited code 0"
But it did not turn on the mobile internet.
