### ISSUE TITLE
App won't open anymore

### ISSUE THREAD

**Issue by shaansheikh** [C-D-Lewis/dashboard#5]
Starting about 3 or so weeks ago (before pebble servers shut down), the dashboard app no longer opens on my pebble. When I try to open it, I see the splash screen, and then it goes back to my list of apps. Uninstalling and reinstalling did not solve the issue.

Any idea why this may be happening? Is this an issue with my app alone, or is it more of a widespread issue? Is there any way I can debug or troubleshoot?

**Comment by C-D-Lewis** [comment]
Can you please try reinstalling both the Android app and Pebble app? And
failing that, the official Pebble Android app as well.

Beyond that, I have nothing more to suggest, as the Pebble app will suffer
changes in Android that no one is around to fix, sadly.

Chris

**Comment by shaansheikh** [comment]
No dice :( Where do you think the issue is? I'm a developer so I can attempt to fix it. Is there some sort of debug mode or some sort of logs I can look at in an attempt to get more information about what's going wrong?

**Comment by C-D-Lewis** [comment]
If you connect to adb, there will be lots of the connection process and sending data to the watch, according to the log statements in the code. You may find something of use in there.

**Comment by jingofett** [comment]
this needs the pebble android app to work?

**Comment by milan0-nbg** [comment]
After update to 4.13 see watchapp won't start anymore.
The 4.12 Version still working

**Comment by C-D-Lewis** [comment]
> After update to 4.13 the watchapp won't start anymore.
> The 4.12 Version still working

I will look into this as soon as I find time, thanks.

**Comment by C-D-Lewis** [comment]
See #6
