### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [C-D-Lewis/dashboard#9]
Great to see this tracker-free app has been revived!

Would you consider offering the Android APK outside the Play Store – e.g. by getting it added to [F-Droid](https://f-droid.org/), or [tagging releases](https://github.com/C-D-Lewis/dashboard/releases) and attach the APK there? For those who cannot use Play, or prefer not to (to avoid being tracked there), that would be great. Thanks in advance!

**Comment by C-D-Lewis** [comment]
Good idea! I have started adding release binaries here.

https://github.com/C-D-Lewis/dashboard/releases/tag/v4.15

**Comment by IzzySoft** [comment]
Cool! Glad you like the idea. I took the freedom to add it to my repo (should show up [here](https://apt.izzysoft.de/fdroid/index/apk/com.wordpress.ninedof.dashboard) with the next sync in about 5-6 hours) to make it easier to be discovered and kept up-to-date – my updater will grab new versions within 24h of your attaching the APK to a new tag, and people using my repo with the F-Droid app will then be notified the same way as you know it from the Play Store app.

Now that the app is available outside of Play Store I think about trying it myself. Just wondering what it might need GMS for (my devices all run LineageOS without GApps). Is that essential? I see it's for location services (`implementation 'com.google.android.gms:play-services-location:17.0.0'`). What feature is that connected to? Does it act based on location somehow? Would *Dashboard* still work if GApps are not present on the device?

**Comment by C-D-Lewis** [comment]
That's cool! Always good to make older apps more freely available.

The location permission is requested related to making Hotspot toggle work on newer Android versions (see recent PR from a fellow contributor). It shouldn't stop other features from working, so please give it a try and see how far you can get when denying it.

**Comment by IzzySoft** [comment]
Thanks! Just added that (abstract, linked here for full details) to the description. Will give it a try soon now that the last doubts have been addressed :smile:

Real tin-foils use a firewall. As no functionality is affected, they can try to block the app from accessing the internet. Luckily my tin foil isn't that thick (I don't say behind every tree is a spy – I just say behind every tree *could be* one :rofl:) Will block location, though. Just to see if that causes any trouble. I haven't used hotspot more than once in about 5 years, so that's not essential to me.

**Comment by IzzySoft** [comment]
OK, two nice pics for you – and two not so nice:

[<img src="https://user-images.githubusercontent.com/6781438/74111363-8792a880-4b94-11ea-8f0c-98e213a98b39.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111363-8792a880-4b94-11ea-8f0c-98e213a98b39.jpg) [<img src="https://user-images.githubusercontent.com/6781438/74111364-882b3f00-4b94-11ea-9e43-a1f279a5df90.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111364-882b3f00-4b94-11ea-9e43-a1f279a5df90.jpg)

This is how it currently looks in the F-Droid client. As you can see, I've just installed your app. Denied the location permission, no crash :smile: But then, I tried to install the Pebble app. Note that I don't have the Pebble app running on my device (never had), but use Gadgetbridge:

[<img src="https://user-images.githubusercontent.com/6781438/74111365-88c3d580-4b94-11ea-9893-e9408f375acc.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111365-88c3d580-4b94-11ea-9893-e9408f375acc.jpg) [<img src="https://user-images.githubusercontent.com/6781438/74111367-88c3d580-4b94-11ea-9ecb-72eaf76b520f.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111367-88c3d580-4b94-11ea-9ecb-72eaf76b520f.jpg)

No way to install the PBW as I cannot get hold of it. Tapping the button only offers web browsers (probably there's the store link behind it). It lacks a link to the PBW file, so Gadgetbridge's installer would pop up. Could you at least call the store page with the developer parameter (`?dev_settings=true` worked on the Pebble store, not sure if Rebble picked that up – oh, they did, good!), so the direct download link becomes visible there.

[<img src="https://user-images.githubusercontent.com/6781438/74111571-e7d61a00-4b95-11ea-83eb-4411e5bfe486.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111571-e7d61a00-4b95-11ea-83eb-4411e5bfe486.jpg) [<img src="https://user-images.githubusercontent.com/6781438/74111673-c3c70880-4b96-11ea-81f3-c1a397751229.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111673-c3c70880-4b96-11ea-81f3-c1a397751229.jpg) [<img src="https://user-images.githubusercontent.com/6781438/74111675-c45f9f00-4b96-11ea-992e-72c986d6f931.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111675-c45f9f00-4b96-11ea-992e-72c986d6f931.jpg)

[<img src="https://user-images.githubusercontent.com/6781438/74111676-c45f9f00-4b96-11ea-9a09-492abc6b670d.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111676-c45f9f00-4b96-11ea-9a09-492abc6b670d.jpg) ![screenshot_20200209-114556](https://user-images.githubusercontent.com/6781438/74111677-c4f83580-4b96-11ea-8aac-3f1ffae463d3.png)

Success! Now I'll play with it a bit the next days… Big thanks again!

**Comment by IzzySoft** [comment]
Another PS: Any idea why XPrivacy reports *Dashboard* tried to use Tracking?

[<img src="https://user-images.githubusercontent.com/6781438/74111821-ac3c4f80-4b97-11ea-9d1b-aa66694e3819.jpg" width="200">](https://user-images.githubusercontent.com/6781438/74111821-ac3c4f80-4b97-11ea-9d1b-aa66694e3819.jpg)

And what seems a bug: whatever sound I chose for "find phone", as soon as I press "OK" *Dashbord* shows it as "Current" but doesn't use it – tapping "choose sound" again shows it was reset to "None". If I try "Default", it only gives a toast "no file chosen, or was unavailable" – and then gives only a little "tock" not really suitable to find the phone unless it's right in front of you. In case it matters: BQ Aquaris X5 Plus running LineageOS 14.1 (Android 7.1.1), no GApps (but microG).

**Comment by IzzySoft** [comment]
@C-D-Lewis I've split off the two problems into separate issues, so you can address them separately. Gets too confusing here otherwise :wink:

**Comment by p4t44** [comment]
Hey, I'm also a Gadgetbridge user who used to use Dashboard (one of my favorite pebble apps, the find phone functionality has saved my phone a few times) but recently (perhaps when I upgraded to android 10?) it stopped working. On opening dashboard it just shows the dashboard icon in the middle of a black screen on the watch and nothing which stays there forever (I've tried this with the android app open and have reinstalled both the android and pebble apps). I assumed this was just a GB issue with an app which hasn't been updated for ages, but now setting that this is back in development and that another GB user has it working I thought I'd ask: have you ever experienced something like this before, or do you know if there is some way to get logs to see what issue is occurring?

Thank you!

**Comment by IzzySoft** [comment]
@p4t44 it starts up fine for me, and seems to work completely (except for the two points mentioned above). Maybe try to install the watchapp fresh? Use the trick I've mentioned (adding `&dev_settings=true` at the end of the URL generated from the "INSTALL/UPDATE" button), then tap the "PBW" button on the bottom of the web page to download, and finally the download notification to install via GB's installer.

If that works for you, I'd be interested to know whether you also have the sound-issue with "find my phone"…

**Comment by p4t44** [comment]
@IzzySoft Yep, I'd done that before but just to be sure I did this now:

- Deleted Dashboard from both watch and cache.
- Deleted Dashboard app
- Restarted Gadgetbridge
- Installed Dashboard from your repo in Aurora Droid
- Download and install watchapp from the Rebble store with dev settings on
- Run app on the watch and phone at the same time and get the eternal loading screen once again.

Unless there's something in here that I'm missing or some setting in GB that could fix it I think I'll try with the Pebble app (just for testing, I'll go back to GB afterwards) and, if the problem persists, open a new issue here.

Are you on Android 10? Given that it used to work for me through Gadgetbridge, that seems like the most likley issue cause for me.

**Comment by IzzySoft** [comment]
Nope, the device I use with my Pebble still runs Nougat (the Oreo update has been promised for 2 years now but never arrived). May I suggest you open a new issue and include device details (Pebble + Android + GB), @p4t44? That seems to be a separate problem, and we shouldn't use this issue here as "catch-all" (to set a good example, I've already split off my two problems left into separate issues as well). If the watchapp hangs *at that phase,* I doubt that has anything to do with the Android part, though – and it might be hard to get logs from the watch (I never tried).
